"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var fs_1 = __importDefault(require("fs"));
var path_1 = require("path");
var src_1 = __importDefault(require("../src"));
var lessContent = '// Generated by @ant-design/aliyun-theme\n\n';
Object.keys(src_1.default).forEach(function (key) {
    var value = src_1.default[key];
    lessContent += key + ": " + value + ";\n";
});
fs_1.default.writeFileSync((0, path_1.join)(process.cwd(), 'index.less'), lessContent);
console.log('✨ Generated index.less successfully!');
