import fs from 'fs';
import { join } from 'path';
import vars from '../src';

let lessContent = '// Generated by @ant-design/aliyun-theme\n\n';

interface Vars {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;
}

Object.keys(vars).forEach((key: string): void => {
  const value = (vars as Vars)[key];
  lessContent += `${key}: ${value};\n`;
});

fs.writeFileSync(join(process.cwd(), 'index.less'), lessContent);
console.log('✨ Generated index.less successfully!');
