"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "error-color": "#fd5451",
    "primary-color": "#0e94cd",
    "table-header-bg": "#f2f5fa",
    "table-header-color": "#333333",
    "table-row-hover-bg": "#f2f5fa",
    "input-height-base": "38px",
    "input-padding-horizontal-base": "15px",
    "input-border-color": "#d2d2d2",
    "input-hover-border-color": "#0e94cd",
    "input-placeholder-color": "#999999",
    "input-color": "#333333",
    "input-disabled-bg": "#f8f8f8",
    "input-disabled-color": "#c9c9c9",
    "icon-color": "#d2d2d2",
    "btn-square-only-icon-size": "18px",
    "select-item-selected-color": "#0e94cd",
    "select-item-selected-bg": "transparent",
    "select-item-active-bg": "#e9f6ff",
    "pagination-item-size": "38px",
    "tabs-horizontal-padding": "12px 24px",
    "tabs-active-color": "#0e94cd",
    "tabs-hover-color": "#56b4dc",
};
